Repository wecode-bootcamp-korea/fullstack2-2nd-ourcodetrip-backend, pull requests merged in 2021-11, with the labels that each got.

#22 Hotfix: dataUploader 일부 수정
  src/utils/dataUploader/dataWriter.js
Labels: Status: Accepted

#25 Modify: Model ServcieCategory, MainCategory, SubCategory에 query 컬럼 추가
  prisma/schema.prisma
Labels: Status: 리뷰 요청

#26 Add: query 컬럼 추가 마이그레이션 파일 추가
  prisma/migrations/20211102084546_modify_categories_add_column_query/migration.sql
Labels: Status: 리뷰 요청

#23 Add: 카카오 회원가입/로그인, 인증인가 미들웨어 구현
  .gitignore
  jest.config.json
  package-lock.json
  package.json
  prisma/migrations/20211101124749_modify_user_password_nullable/migration.sql
  prisma/schema.prisma
  src/app.js
  src/controllers/index.js
  src/controllers/userController.js
  src/middlewares/passport.js
  src/models/index.js
  src/models/userDao.js
  src/routes/index.js
  src/routes/userRouter.js
  src/services/index.js
  src/services/userService.js
  src/utils/dataUploader/csv/userProfileImage.csv
  src/utils/dataUploader/dataUploader.js
  tests/data/sample.js
  tests/data/user.js
  tests/sample.test.js
  tests/user.test.js
Labels: Status: 리뷰 요청

#24 [category] Add: 카테고리 조회 API 구현중
  package-lock.json
  src/controllers/categoryController.js
  src/controllers/index.js
  src/models/categoryDao.js
  src/models/index.js
  src/routes/categoryRouter.js
  src/routes/index.js
  src/services/categoryService.js
  src/services/index.js
  src/utils/dataUploader/csv/city.csv
  src/utils/dataUploader/csv/cityImage.csv
  src/utils/dataUploader/csv/country.csv
  src/utils/dataUploader/csv/imageType.csv
  src/utils/dataUploader/csv/mainCategory.csv
  src/utils/dataUploader/csv/optionList.csv
  src/utils/dataUploader/csv/partner.csv
  src/utils/dataUploader/csv/product.csv
  src/utils/dataUploader/csv/productImage.csv
  src/utils/dataUploader/csv/productOption.csv
  src/utils/dataUploader/csv/productType.csv
  src/utils/dataUploader/csv/serviceCategory.csv
  src/utils/dataUploader/csv/subCategory.csv
  src/utils/dataUploader/csv/ticket.csv
  src/utils/dataUploader/csv/ticketOption.csv
  src/utils/dataUploader/csv/tour.csv
  src/utils/dataUploader/csv/user.csv
  src/utils/dataUploader/dataReader.js
  src/utils/dataUploader/dataUploader.js
  tests/categories.test.js
  tests/data/categories.js
Labels: Status: 리뷰 요청

#27 Add: 후기 조회, 더보기 API 구현
  prisma/migrations/20211102172723_modify_some_fk_column_add_unique_constraint/migration.sql
  prisma/schema.prisma
  src/controllers/index.js
  src/controllers/reviewController.js
  src/controllers/userController.js
  src/models/index.js
  src/models/reviewDao.js
  src/models/userDao.js
  src/routes/index.js
  src/routes/reviewRouter.js
  src/routes/userRouter.js
  src/services/index.js
  src/services/reviewService.js
  src/services/userService.js
  src/utils/dataUploader/csv/platform.csv
  src/utils/dataUploader/csv/test.csv
  src/utils/dataUploader/csv/userProfileImage.csv
  tests/data/review.js
  tests/review.test.js
Labels: Status: 리뷰 요청

#28 Add: 위시리스트 추가/삭제, 내 위시리스트 API 구현
  prisma/migrations/20211103091431_add_model_ticket_add_column_discount_rate/migration.sql
  prisma/schema.prisma
  src/app.js
  src/controllers/userController.js
  src/models/index.js
  src/models/productDao.js
  src/models/userDao.js
  src/passport.js
  src/routes/userRouter.js
  src/services/index.js
  src/services/productService.js
  src/services/reviewService.js
  src/services/userService.js
  src/utils/dataUploader/csv/city.csv
  src/utils/dataUploader/csv/cityImage.csv
  src/utils/dataUploader/csv/country.csv
  src/utils/dataUploader/csv/imageType.csv
  src/utils/dataUploader/csv/mainCategory.csv
  src/utils/dataUploader/csv/optionList.csv
  src/utils/dataUploader/csv/partner.csv
  src/utils/dataUploader/csv/product.csv
  src/utils/dataUploader/csv/productImage.csv
  src/utils/dataUploader/csv/productOption.csv
  src/utils/dataUploader/csv/productType.csv
  src/utils/dataUploader/csv/serviceCategory.csv
  src/utils/dataUploader/csv/subCategory.csv
  src/utils/dataUploader/csv/ticket.csv
  src/utils/dataUploader/csv/ticketOption.csv
  src/utils/dataUploader/csv/tour.csv
  src/utils/dataUploader/csv/user.csv
  src/utils/dataUploader/dataUploader.js
  src/utils/errors.js
  tests/user.test.js
Labels: Status: 리뷰 요청

#29 Add: 유저 프로필 관련 API 구현
  src/app.js
  src/controllers/userController.js
  src/middlewares/passportJwt.js
  src/models/userDao.js
  src/routes/userRouter.js
  src/services/userService.js
Labels: Status: Accepted

#30 Add: schema 수정 - Classifiation, ClassificationProduct 모델 추가
  prisma/migrations/20211103155936_add_model_classification_and_classification_product/migration.sql
  prisma/schema.prisma
Labels: Status: Accepted

#32 Add: 상품 분류별 조회 / 상품 리스트 필터링 및 정렬 API 구현
  prisma/migrations/20211103205541_add_model_classification_remove_query/migration.sql
  prisma/schema.prisma
  src/app.js
  src/controllers/productController.js
  src/models/productDao.js
  src/models/reviewDao.js
  src/routes/index.js
  src/routes/productRotuer.js
  src/services/productService.js
  src/services/reviewService.js
  src/services/userService.js
  src/utils/dataUploader/dataUploader.js
  src/utils/queryStringMapper.js
Labels: Status: Accepted

#31 Add: 상품 상세 정보 조회 API 구현
  src/app.js
  src/controllers/index.js
  src/controllers/productController.js
  src/controllers/userController.js
  src/middlewares/passportJwt.js
  src/models/index.js
  src/models/productDao.js
  src/routes/categoryRouter.js
  src/routes/index.js
  src/routes/productRouter.js
  src/services/index.js
  src/services/productService.js
  src/services/reviewService.js
  src/utils/dataUploader/dataUploader.js
  src/utils/queryStringMapper.js
Labels: Status: 리뷰 요청

#33 Hot fix: CityImage 모델에 imageTypeId 컬럼 추가
  prisma/migrations/20211104183632_add_model_city_image_image_type_id/migration.sql
  prisma/schema.prisma
Labels: Status: Accepted

#35 Hot fix: userDao.js - getPlatformIdByName 수정
  src/models/userDao.js
Labels: Status: Accepted

#36 Add: README.md 업데이트
  README.md
Labels: Status: Accepted

#39 Fixed: query filtering & wishlist 버그 수정
  src/models/productDao.js
  src/services/productService.js
Labels: Status: 수정 요청

#40 hot fix - subCategory 필터링 로직 수정
  .env.deployment
  Dockerfile
  package.json
  src/controllers/productController.js
  src/controllers/userController.js
  src/models/productDao.js
  src/services/productService.js
Labels: Status: Accepted

#42 hot fix - .env.deployment 삭제
  .env.deployment
  .gitignore
Labels: Status: Accepted
